name: Website Docker Release

on: [ push, pull_request ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:  "***/faf-website"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build Docker Image
        uses: docker/build-push-action@v5
      -
        name: Push Docker Image
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'develop' || startsWith(github.ref, 'refs/tags') }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      
